[package]
name = "jabroni"
version = "0.1.0"
edition = "2021"
rust-version = "1.58"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enum-as-inner = "0.3.3"
pest = "2.1.3"
pest_derive = "2.1.0"
thiserror = "1.0.30"
